print('NUMERICAL:')
print('int : combination of numbers', 10, sep = '\n')
print('float : decimal values', 8.2, sep = '\n')
print('complex : imaginary values',3+3j, sep = '\n', end = '\n\n')
print('SEQUENTIAL DT:')
print('string : combination of characters', 'Anjusree', sep = '\n')
print('list : collection of items', [2,3,4,5], sep = '\n')
print('tuple : collection of items', (2,3,4,5), sep = '\n', end = '\n\n')
print('MAPPING DT:')
print('set : collection of items', {2,3,4,5}, sep = '\n')
print('dictionary : stores data in key-value pair', {'1':'1','2':'4','3':'9','4':'16'}, sep = '\n', end = '\n\n')
print('extra')
print('boolean : has only two values', True, False, sep = '\n')
print('none : empty data, can be used later')

